-- =============================================================================
-- Migration v38 — Web Push for management alerts
-- =============================================================================
--
-- WHY THIS EXISTS
--
-- Overdue and unassigned tasks were only ever seen by someone opening the
-- Alerts page. The Settings page has had a "Push Notifications" toggle since
-- v1 that wrote a preference and did nothing else. This is the storage and
-- the schedule that make it real; the sending lives in the alert-push Edge
-- Function and the subscribing in src/lib/push.ts.
--
-- WHAT CHANGES
--
--   push_subscriptions   one row per browser that opted in (endpoint + keys)
--   push_vapid           the VAPID public key, readable by any signed-in staff
--   vault                the VAPID private key, reachable only through
--                        push_vapid_private_key(), which only service_role
--                        may call
--   run_alert_push()     the pg_cron hook, same shape as run_calendar_syncs()
--                        in v18: service-role key from Vault, fire-and-forget
--                        net.http_post to the function
--
-- The keypair is generated by the Edge Function on its first call and stored
-- through push_vapid_store(); nothing has to be pasted into a dashboard.
--
-- WHAT DOES NOT CHANGE
--
-- profiles.notification_preferences keeps being the person's stated wish;
-- the function honours pushEnabled and overdueAlerts from it. A row here
-- without the preference sends nothing, and the preference without a row
-- here has nowhere to send to.
--
-- iOS: Web Push only reaches sites installed to the Home Screen. Settings
-- says so before offering the toggle.

-- ---------------------------------------------------------------- subscriptions

create table if not exists public.push_subscriptions (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references public.profiles(id) on delete cascade,
  endpoint     text not null unique,
  p256dh       text not null,
  auth         text not null,
  user_agent   text,
  created_at   timestamptz not null default now(),
  last_sent_at timestamptz,
  failures     integer not null default 0
);

create index if not exists push_subscriptions_user_idx
  on public.push_subscriptions (user_id);

alter table public.push_subscriptions enable row level security;

revoke all on public.push_subscriptions from public, anon;
grant select, insert, update, delete on public.push_subscriptions to authenticated;

-- Your own rows only. Management does not need to see each other's
-- endpoints, and the sender runs as service_role, which bypasses this.
drop policy if exists push_subscriptions_own on public.push_subscriptions;
create policy push_subscriptions_own on public.push_subscriptions
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- ---------------------------------------------------------------- VAPID keys

-- Single-row table: the boolean primary key with a CHECK is the idiom for
-- "there can only be one".
create table if not exists public.push_vapid (
  id          boolean primary key default true check (id),
  public_key  text not null,
  created_at  timestamptz not null default now()
);

alter table public.push_vapid enable row level security;
revoke all on public.push_vapid from public, anon;
grant select on public.push_vapid to authenticated;

drop policy if exists push_vapid_read on public.push_vapid;
create policy push_vapid_read on public.push_vapid
  for select to authenticated using (true);

-- Store a freshly generated pair. Public half in the table, private half in
-- Vault. Definer so it can reach vault; callable by service_role alone.
create or replace function public.push_vapid_store(p_public text, p_private text)
returns void
language plpgsql
security definer
set search_path = public, vault
as $$
begin
  insert into public.push_vapid (id, public_key) values (true, p_public)
    on conflict (id) do update set public_key = excluded.public_key, created_at = now();
  perform vault.create_secret(p_private, 'vapid_private_key', 'Web Push VAPID private key (v38)');
end;
$$;

revoke all on function public.push_vapid_store(text, text) from public, anon, authenticated;
grant execute on function public.push_vapid_store(text, text) to service_role;

create or replace function public.push_vapid_private_key()
returns text
language sql
stable
security definer
set search_path = public, vault
as $$
  select decrypted_secret
  from vault.decrypted_secrets
  where name = 'vapid_private_key'
  order by created_at desc
  limit 1
$$;

revoke all on function public.push_vapid_private_key() from public, anon, authenticated;
grant execute on function public.push_vapid_private_key() to service_role;

-- ---------------------------------------------------------------- cron hook

create extension if not exists pg_net;
create extension if not exists pg_cron;

-- Same pattern as run_calendar_syncs() (v18): the service-role key comes out
-- of Vault at call time, and the POST is fire-and-forget so a slow function
-- never holds a cron worker.
create or replace function public.run_alert_push()
returns void
language plpgsql
security definer
set search_path = public, extensions, vault, net
as $$
declare
  key text;
begin
  select decrypted_secret into key
  from vault.decrypted_secrets
  where name = 'service_role_key'
  limit 1;

  if key is null then
    raise exception 'vault secret service_role_key is missing';
  end if;

  perform net.http_post(
    url := 'https://sgppeenmvskwztaszkgn.supabase.co/functions/v1/alert-push',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || key
    ),
    body := '{"source":"cron"}'::jsonb,
    timeout_milliseconds := 55000
  );
end;
$$;

revoke all on function public.run_alert_push() from public, anon, authenticated;

-- ---------------------------------------------------------------- schedule
--
-- A call, not DDL, so it sits at the end and re-running it is how the time
-- is changed. 15:00 UTC is 8am Pacific in summer and 7am in winter (the
-- studio's Google calendars are in America/Los_Angeles) — early enough to be
-- the first thing seen, late enough that yesterday's tasks have actually
-- become overdue in local time.

select cron.schedule(
  'alert-push-daily',
  '0 15 * * *',
  $$select public.run_alert_push()$$
);
